kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '1754888526'
  name: tpex-admin-service
  uid: 35846607-3321-407a-a84b-5c28e477ce0a
  creationTimestamp: '2023-02-27T06:11:51Z'
  generation: 420
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2023-08-21T10:39:16Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime-namespace': {}
        'f:spec':
          'f:replicas': {}
          'f:selector':
            .: {}
            'f:app': {}
            'f:deploymentconfig': {}
          'f:strategy':
            'f:activeDeadlineSeconds': {}
            'f:resources':
              'f:limits':
                .: {}
                'f:cpu': {}
                'f:memory': {}
              'f:requests':
                .: {}
                'f:cpu': {}
                'f:memory': {}
            'f:rollingParams':
              .: {}
              'f:intervalSeconds': {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
              'f:timeoutSeconds': {}
              'f:updatePeriodSeconds': {}
            'f:type': {}
          'f:template':
            .: {}
            'f:metadata':
              .: {}
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:creationTimestamp': {}
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
            'f:spec':
              .: {}
              'f:containers':
                .: {}
                'k:{"name":"tpex-admin-service"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":9090,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/home/TMAP/DSD/shared"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/tmp"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"pvc-ds9-dev-01"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
                'k:{"name":"tpex-admin-service-1"}':
                  .: {}
                  'f:emptyDir': {}
                  'f:name': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2023-08-30T12:33:00Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"tpex-admin-service"}':
                  'f:image': {}
          'f:triggers': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2023-08-30T12:33:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:updatedReplicas': {}
          'f:readyReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:details':
            .: {}
            'f:causes': {}
            'f:message': {}
          'f:replicas': {}
          'f:availableReplicas': {}
          'f:observedGeneration': {}
          'f:unavailableReplicas': {}
          'f:latestVersion': {}
      subresource: status
  namespace: ds9-dev
  labels:
    app: tpex-admin-service
    app.kubernetes.io/component: tpex-admin-service
    app.kubernetes.io/instance: tpex-admin-service
    app.kubernetes.io/name: tpex-admin-service
    app.kubernetes.io/part-of: tpex-admin-service
    app.openshift.io/runtime-namespace: ds9-dev
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
      limits:
        cpu: 400m
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 900Mi
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - tpex-admin-service
        from:
          kind: ImageStreamTag
          namespace: ds9-dev
          name: 'tpex-admin-service:latest'
        lastTriggeredImage: >-
          tcr.ap.toyota-asia.com/toyota-part-export-system/tpex-admin-service@sha256:2b9a2ee9d3679533803699e6fe8053b434fd938385edeb5a3c2e502e603e1eec
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: tpex-admin-service
    deploymentconfig: tpex-admin-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tpex-admin-service
        deploymentconfig: tpex-admin-service
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: tpex-admin-service-1
          emptyDir: {}
        - name: pvc-ds9-dev-01
          persistentVolumeClaim:
            claimName: pvc-ds9-dev-01
      containers:
        - name: tpex-admin-service
          image: >-
            tcr.ap.toyota-asia.com/toyota-part-export-system/tpex-admin-service@sha256:2b9a2ee9d3679533803699e6fe8053b434fd938385edeb5a3c2e502e603e1eec
          ports:
            - containerPort: 9090
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 900Mi
          volumeMounts:
            - name: tpex-admin-service-1
              mountPath: /tmp
            - name: pvc-ds9-dev-01
              mountPath: /home/TMAP/DSD/shared
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 420
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: DockerImage
            name: >-
              tcr.ap.toyota-asia.com/toyota-part-export-system/tpex-admin-service@sha256:2b9a2ee9d3679533803699e6fe8053b434fd938385edeb5a3c2e502e603e1eec
  availableReplicas: 1
  unavailableReplicas: 0
  latestVersion: 335
  updatedReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-08-25T09:33:47Z'
      lastTransitionTime: '2023-08-25T09:33:47Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-08-30T12:33:13Z'
      lastTransitionTime: '2023-08-30T12:33:09Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "tpex-admin-service-335" successfully rolled out
  replicas: 1
  readyReplicas: 1
